import { MoodConfig, MoodType } from '../types';

export const MOODS: Record<MoodType, MoodConfig> = {
  happy: {
    type: 'happy',
    label: 'Happy',
    name: 'Happy',
    color: '#eb3f63',
    gradient: 'linear-gradient(135deg, #f05273 0%, #db2750 100%)',
    glowColor: 'rgba(235, 63, 99, 0.45)',
    textColor: '#83182b',
    flowerColor: '#d92c52',
    petalBg: '#f26280',
    strokeColor: '#b81e41',
    description: 'Joyful, inspired, energized & grateful',
    iconSvg: 'happy-flower',
  },
  neutral: {
    type: 'neutral',
    label: 'Neutral',
    name: 'Neutral',
    color: '#f5b525',
    gradient: 'linear-gradient(135deg, #fbc337 0%, #e89e13 100%)',
    glowColor: 'rgba(245, 181, 37, 0.45)',
    textColor: '#855702',
    flowerColor: '#e59f0f',
    petalBg: '#fbc337',
    strokeColor: '#b87c05',
    description: 'Calm, balanced, steady & reflective',
    iconSvg: 'neutral-flower',
  },
  sad: {
    type: 'sad',
    label: 'Sad/Tired',
    name: 'Sad / Tired',
    color: '#a861d8',
    gradient: 'linear-gradient(135deg, #bb78e8 0%, #8e42c2 100%)',
    glowColor: 'rgba(168, 97, 216, 0.45)',
    textColor: '#571c7a',
    flowerColor: '#a14ecc',
    petalBg: '#bb78e8',
    strokeColor: '#6d2698',
    description: 'Low energy, exhausted, melancholic or resting',
    iconSvg: 'sad-flower',
  },
};

export const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const PRESET_TAGS = [
  'Grateful',
  'Productive',
  'Family',
  'Friends',
  'Work',
  'Rest',
  'Outdoors',
  'Exercise',
  'Creative',
  'Mindful',
  'Overwhelmed',
  'Peaceful',
];
